<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gesture_command</name>
  <version>3.0.0</version>
  <description>Máy trạng thái an toàn: cử chỉ -> vận tốc GUIDED / set_mode / takeoff qua MAVROS.</description>
  <maintainer email="phaphim2905@gmail.com">Nguyen Pha Phim</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>mavros_msgs</exec_depend>
  <exec_depend>gesture_interfaces</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
