<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gesture_bringup</name>
  <version>3.0.0</version>
  <description>Launch file, tham số và model: camera_only, sitl, real, gazebo.</description>
  <maintainer email="phaphim2905@gmail.com">Nguyen Pha Phim</maintainer>
  <license>MIT</license>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>gesture_interfaces</exec_depend>
  <exec_depend>gesture_perception</exec_depend>
  <exec_depend>gesture_command</exec_depend>
  <exec_depend>mavros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
